# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0f8b7a36b7d1136c367815f21abcdfe98ebbcffa39168878376178d32a80c44926475a5acd655cc4b0126d58a30de23c5bf25e314c3becd6c63076a53827d5d2

test:
  secret_key_base: 4ffa99907a4e2497156133c368661d83c9e17e5e9c779cee12ed6dd2de7d6f91e558c13694bec2709b6fc9c705f4262d1691f0f357170ea2a9563bc4c4a8fd73

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
